# thuli development environment. Usage: source scripts/env.sh
# Generated by scripts/install.sh; safe to edit OPAMROOT / OCAML_SWITCH below.
export OPAMROOT="${OPAMROOT:-${HOME}/.opam}"
export OCAML_SWITCH="${OCAML_SWITCH:-5.5.0}"
export PATH="${HOME}/.local/bin:/usr/local/bin:${PATH}"
if command -v opam >/dev/null 2>&1; then
  eval "$(OPAMROOT="${OPAMROOT}" opam env --switch="${OCAML_SWITCH}")"
fi
